### PR TITLE
Adding projects to homepage

### LINKED ISSUE #4: Enhancement: Add these projects
Add these projects in the cards where daffodil is written on the Home page. Add a relevant image and one-line content to it.

1. Daffodil (https://github.com/Webwiznitr/Project-daffodil)
2. Clubopedia (https://github.com/Webwiznitr/Project-keppel)
3. Webdev Roadmap (https://webwiz.notion.site/webwiz/Road-map-to-became-Web-Beast-Webwiz-7b0334c890c7482a9738687b757a92da)

### PR DESCRIPTION
**Pull request by vijaykrishna536**
## Issue
#4 

Hi @kumarshantanu01 
Please help to review and merge
Screenshot of changes attached
Screenshot 2021-10-29 at 7 34 28 PM

### CODE REVIEW

**Comment by kumarshantanu01** [comment]
@vijaykrishna536 change the text of the button to "visit"
and add these links in the buttons-
Daffodil  (https://webwiznitr.github.io/Project-daffodil/)
Clubopedia (https://clubopedia.netlify.app/)
WWebdev Roadmap (https://webwiz.notion.site/webwiz/Road-map-to-became-Web-Beast-Webwiz-7b0334c890c7482a9738687b757a92da)

**Comment by kumarshantanu01** [comment]
and change a little css of the button, you can add violet color to the button

**Comment by vijaykrishna536** [comment]
Hi @kumarshantanu01 
Have updated the PR with requested changes
Screenshot attached
Screenshot 2021-10-29 at 11 07 54 PM

**Comment by kumarshantanu01** [comment]
Great ork @vijaykrishna536

**Pull request merged**
