### PR TITLE
Added Typeform for Join Us

### LINKED ISSUE #1: Add a typeform link to the join us button in the navbar.
In the Typeform add all the required questions.

### PR DESCRIPTION
**Pull request by samrath-sudesh-acharya**

### CODE REVIEW

**Comment by samrath-sudesh-acharya** [comment]
name

**Comment by samrath-sudesh-acharya** [comment]
the typeform is like this

**Comment by samrath-sudesh-acharya** [comment]
@kumarshantanu01  why does the pull request say the project not participating in hacktoberfest website

**Comment by kumarshantanu01** [comment]
Don't know about it but I have added hacktoberfest-accepted in pull request and hacktoberfest banner in readme also.

**Comment by samrath-sudesh-acharya** [comment]
ok thanks it working

**Pull request merged**
